server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

# Phase 0 routes + health
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**, /core-actuator/**
          filters:
            - StripPrefix=0
        - id: ai-service
          uri: http://localhost:8082
          predicates:
            - Path=/ai/**, /ai-actuator/**
          filters:
            - StripPrefix=0
      default-filters:
        - SaveSession
