server:
  port: 8082

spring:
  application:
    name: ai-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
